### ISSUE TITLE
Cannot run js tests

### ISSUE THREAD

**Issue by HarlemSquirrel** [learn-co-students/js-tictactoe-rails-api-v-000#6]
When running `learn test` only the controller tests run. Trying `learn test spec/tictactoe.spec.js` or `rspec spec/tictactoe.spec.js` renders this error:

```
$ rspec spec/tictactoe.spec.js 
/home/mm/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1361:in `load': /home/mm/code/labs/js-tictactoe-rails-api-v-000/spec/tictactoe.spec.js:14: `$(' is not allowed as a global variable name (SyntaxError)
/home/mm/code/labs/js-tictactoe-rails-api-v-000/spec/tictactoe.spec.js:14: syntax error, unexpected end-of-input, expecting '}'
      $(selector).click();
       ^
    from /home/mm/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1361:in `block in load_spec_files'
    from /home/mm/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1359:in `each'
    from /home/mm/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1359:in `load_spec_files'
    from /home/mm/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:106:in `setup'
    from /home/mm/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:92:in `run'
    from /home/mm/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:78:in `run'
    from /home/mm/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:45:in `invoke'
    from /home/mm/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/exe/rspec:4:in `<top (required)>'
    from /home/mm/.rbenv/versions/2.2.2/bin/rspec:23:in `load'
    from /home/mm/.rbenv/versions/2.2.2/bin/rspec:23:in `<main>'
```

ShanaLMoore reports that `sudo learn` works but this does not work for me on Ubuntu 14.04

**Comment by HarlemSquirrel** [comment]
OK, I got it working on Ubuntu 14.04 by installing ruby 2.2.4 with rbenv. 

I updated rbenv and ruby-build, installed ruby 2.2.4, then installed the learn-co gem
```
cd ~/.rbenv
git pull
cd plugins/ruby-build
git pull
rbenv install 2.2.4
rbenv local 2.2.4
gem install learn-co
```

**Comment by ktravers** [comment]
thanks for the workaround @HarlemSquirrel!
